In [100]:
import pandas as pd

In [101]:
# Criando Dataframes

## Selecionando colunas de interesse para análise
colunas_selecionadas = ['Código', 'Identificador do indivíduo', 'Instituição executora', 'Estado', 'Cidade', 'Praia', 'Trecho', 'Estratégia do trecho', 'Condição do céu inicial', 'Condição do mar inicial', 'Maré inicial', 'Vento inicial', 'Tipo do monitoramento', 'Data/Hora', 'Ponto - Lat', 'Ponto - Long', 'Espécies - Classe', 'Espécies - Ordem', 'Espécies - Subordem', 'Espécies - Família', 'Espécies - Gênero', 'Espécies - Espécie', 'Espécie ameaçada', 'Caracterização do ambiente', 'Condição']

BC_ES_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\BC_ES.csv')[colunas_selecionadas]
BS_SC_PR_bruto = pd.read_csv(r'c:\Users\taina\Documents\PMP_dados\BS_SC_PR.csv')[colunas_selecionadas]
BS_SP_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\BS_SP.csv')[colunas_selecionadas]
BS_RJ_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\BS_RJ.csv')[colunas_selecionadas]
RN_CE_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\RN_CE.csv')[colunas_selecionadas]
SE_AL_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\SE_AL.csv')[colunas_selecionadas]

C:\Users\taina\AppData\Local\Temp\ipykernel_9692\1383851217.py:6: DtypeWarning: Columns (47,54,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  BC_ES_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\BC_ES.csv')[colunas_selecionadas]
C:\Users\taina\AppData\Local\Temp\ipykernel_9692\1383851217.py:7: DtypeWarning: Columns (33,56,96,99,100,101,103,104,105,107,108,109,110,111,114,115) have mixed types. Specify dtype option on import or set low_memory=False.
  BS_SC_PR_bruto = pd.read_csv(r'c:\Users\taina\Documents\PMP_dados\BS_SC_PR.csv')[colunas_selecionadas]
C:\Users\taina\AppData\Local\Temp\ipykernel_9692\1383851217.py:8: DtypeWarning: Columns (33,54,55,96,99,101,110,115,116) have mixed types. Specify dtype option on import or set low_memory=False.
  BS_SP_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\BS_SP.csv')[colunas_selecionadas]
C:\Users\taina\AppData\Local\Temp\ipykernel_9692\1383851217.py:9: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  BS_RJ_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\BS_RJ.csv')[colunas_selecionadas]
C:\Users\taina\AppData\Local\Temp\ipykernel_9692\1383851217.py:11: DtypeWarning: Columns (33,42,47,89,92,93,94,95,97,98,99,100,101,102,106,108,109) have mixed types. Specify dtype option on import or set low_memory=False.
  SE_AL_bruto = pd.read_csv(r'C:\Users\taina\Documents\PMP_dados\SE_AL.csv')[colunas_selecionadas]

In [102]:
dataframes = {'BC_ES': BC_ES_bruto,
 'BS_SC_PR': BS_SC_PR_bruto,
 'BS_SP': BS_SP_bruto,
 'BS_RJ': BS_RJ_bruto,
 'RN_CE': RN_CE_bruto,
 'SE_AL': SE_AL_bruto
}

In [103]:
# Exemplo de dataset
BC_ES_bruto.head()

,Código,Identificador do indivíduo,Instituição executora,Estado,Cidade,Praia,Trecho,Estratégia do trecho,Condição do céu inicial,Condição do mar inicial,...,Ponto - Long,Espécies - Classe,Espécies - Ordem,Espécies - Subordem,Espécies - Família,Espécies - Gênero,Espécies - Espécie,Espécie ameaçada,Caracterização do ambiente,Condição
0,327414,758929,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Itapemirim,Itaipava,4B01,Diário,Aberto,2,...,-40.7740,Reptilia,Testudines,Cryptodira,Cheloniidae,Chelonia,Chelonia mydas,Não,Arenoso,Morto
1,327413,758920,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Marataízes,Cações,4B02,Diário,Parcialmente nublado,1,...,-40.8710,Reptilia,Testudines,Cryptodira,Cheloniidae,Chelonia,Chelonia mydas,Não,Arenoso,Morto
2,327411,758912,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Marataízes,Lagoa Dantas,4B02,Diário,Parcialmente nublado,3,...,-40.8507,Reptilia,Testudines,Cryptodira,Cheloniidae,Chelonia,Chelonia mydas,Não,Arenoso,Morto
3,327409,758899,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Marataízes,Barra,4B02,Diário,Parcialmente nublado,1,...,-40.8116,Reptilia,Testudines,Cryptodira,Cheloniidae,Chelonia,Chelonia mydas,Não,Arenoso,Morto
4,327369,758877,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Anchieta,Castelhanos,4A05,Acionamento,Aberto,2,...,-40.6224,Reptilia,Testudines,Cryptodira,Cheloniidae,Chelonia,Chelonia mydas,Não,Arenoso,Vivo

In [104]:
for nome, df in dataframes.items():
    print(f'{nome}: {df.shape}')

BC_ES: (24237, 25)
BS_SC_PR: (51692, 25)
BS_SP: (23555, 25)
BS_RJ: (10560, 25)
RN_CE: (3488, 25)
SE_AL: (9246, 25)

In [105]:
# Checando duplicatas

for nome, df in dataframes.items():
    print(f'{nome}: {df.duplicated().sum()} registros duplicados')

BC_ES: 0 registros duplicados
BS_SC_PR: 0 registros duplicados
BS_SP: 0 registros duplicados
BS_RJ: 0 registros duplicados
RN_CE: 0 registros duplicados
SE_AL: 0 registros duplicados

In [106]:
# Checando nulos

for nome, df in dataframes.items():
    print(nome)
    print(df.isna().sum()[df.isna().sum() > 0])
    print('-' * 33)

BC_ES
Condição do céu inicial       1
Condição do mar inicial       1
Maré inicial                  1
Vento inicial                 1
Tipo do monitoramento        99
Espécies - Subordem        4407
Espécies - Família           42
Espécies - Gênero            78
Espécies - Espécie          140
Espécie ameaçada            140
dtype: int64
---------------------------------
BS_SC_PR
Espécies - Ordem           2
Espécies - Subordem    37706
Espécies - Família       104
Espécies - Gênero        230
Espécies - Espécie       668
Espécie ameaçada         668
dtype: int64
---------------------------------
BS_SP
Condição do céu inicial       13
Condição do mar inicial       13
Maré inicial                  13
Vento inicial                 13
Tipo do monitoramento        148
Espécies - Subordem        12250
Espécies - Família            95
Espécies - Gênero            327
Espécies - Espécie           661
Espécie ameaçada             661
dtype: int64
---------------------------------
BS_RJ
Condição do céu inicial       4
Condição do mar inicial       4
Maré inicial                  4
Vento inicial                 4
Tipo do monitoramento        13
Espécies - Subordem        5929
Espécies - Família           47
Espécies - Gênero            98
Espécies - Espécie          363
Espécie ameaçada            363
dtype: int64
---------------------------------
RN_CE
Estado                     143
Cidade                     143
Praia                      143
Trecho                     143
Estratégia do trecho       143
Condição do céu inicial    155
Condição do mar inicial    156
Maré inicial               158
Vento inicial              156
Tipo do monitoramento      267
Espécies - Subordem        476
Espécies - Família          20
Espécies - Gênero           51
Espécies - Espécie         105
Espécie ameaçada           105
dtype: int64
---------------------------------
SE_AL
Condição do céu inicial       4
Condição do mar inicial       4
Maré inicial                  4
Vento inicial                 4
Tipo do monitoramento        65
Espécies - Ordem              4
Espécies - Subordem        3366
Espécies - Família           48
Espécies - Gênero            77
Espécies - Espécie          755
Espécie ameaçada            755
dtype: int64
---------------------------------

In [107]:
def calcular_porcentagem_nulos(df, nome):
    total_linhas = len(df)
    total_nulos = df['Espécie ameaçada'].isnull().sum()
    porcentagem_nulos = (total_nulos / total_linhas) * 100
    print(f"{nome}: {porcentagem_nulos:.2f}% de valores nulos")

for nome, df in dataframes.items():
    calcular_porcentagem_nulos(df, nome)

BC_ES: 0.58% de valores nulos
BS_SC_PR: 1.29% de valores nulos
BS_SP: 2.81% de valores nulos
BS_RJ: 3.44% de valores nulos
RN_CE: 3.01% de valores nulos
SE_AL: 8.17% de valores nulos

In [116]:
colunas_dispensaveis = ['Trecho', 'Condição do céu inicial', 'Condição do mar inicial', 'Tipo do monitoramento', 'Espécies - Subordem', 'Espécies - Família', 'Espécies - Gênero']
dfs_drop = {}

for nome,df in dataframes.items():
    df_drop = df.drop(columns=colunas_dispensaveis)
    dfs_drop[nome] = df_drop

dfs_drop['BC_ES']

,Código,Identificador do indivíduo,Instituição executora,Estado,Cidade,Praia,Estratégia do trecho,Maré inicial,Vento inicial,Data/Hora,Ponto - Lat,Ponto - Long,Espécies - Classe,Espécies - Ordem,Espécies - Espécie,Espécie ameaçada,Caracterização do ambiente,Condição
0,327414,758929,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Itapemirim,Itaipava,Diário,Enchente,2 - Brisa leve – 6 até 11 km/h,2/11/2024 11:49,-20.894300,-40.774000,Reptilia,Testudines,Chelonia mydas,Não,Arenoso,Morto
1,327413,758920,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Marataízes,Cações,Diário,Vazante,1 - Leve – 1 até 5km/h,2/11/2024 8:37,-21.135700,-40.871000,Reptilia,Testudines,Chelonia mydas,Não,Arenoso,Morto
2,327411,758912,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Marataízes,Lagoa Dantas,Diário,Vazante,3 - Brisa suave – 12 até 19 km/h,2/11/2024 6:30,-21.105900,-40.850700,Reptilia,Testudines,Chelonia mydas,Não,Arenoso,Morto
3,327409,758899,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Marataízes,Barra,Diário,Vazante,1 - Leve – 1 até 5km/h,2/11/2024 7:48,-21.025900,-40.811600,Reptilia,Testudines,Chelonia mydas,Não,Arenoso,Morto
4,327369,758877,Instituto de Pesquisa e Conservação Marinha - ...,Espírito Santo,Anchieta,Castelhanos,Acionamento,Vazia,2 - Brisa leve – 6 até 11 km/h,2/11/2024 11:06,-20.834400,-40.622400,Reptilia,Testudines,Chelonia mydas,Não,Arenoso,Vivo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24232,115963,150487,Ambipar Response,Espírito Santo,Vitória,Canto,Diário,Enchente,2 - Brisa leve – 6 até 11 km/h,1/1/2020 14:42,-20.299100,-40.290100,Reptilia,Testudines,Chelonia mydas,Não,Água,Vivo
24233,115934,182600,Ambipar Response,Rio de Janeiro,Cabo Frio,Rasa,Diário,Vazante,5 - Brisa moderada – 30 a 38 km/h,1/1/2020 10:26,-22.730110,-41.972400,Aves,Suliformes,Sula leucogaster,Não,Arenoso,Vivo
24234,115922,186299,Ambipar Response,Espírito Santo,São Mateus,Guriri,Diário,Cheia,1 - Leve – 1 até 5km/h,1/1/2020 7:50,-18.787580,-39.748450,Mammalia,Cetacea,Pontoporia blainvillei,Sim,Arenoso,Morto
24235,115920,185444,Ambipar Response,Espírito Santo,Serra,Falésias,Diário,Cheia,1 - Leve – 1 até 5km/h,1/1/2020 7:38,-20.067175,-40.180950,Reptilia,Testudines,Chelonia mydas,Não,Arenoso,Morto
24236,115911,185154,Ambipar Response,Rio de Janeiro,São Francisco de Itabapoana,São Francisco Norte,Diário,Enchente,0 - Calmo – até 1 km/h,1/1/2020 7:16,-21.319896,-40.961136,Reptilia,Testudines,Chelonia mydas,Não,Arenoso,Morto